name: .NET Core

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      sln-file: src/CosmosToolbox.sln

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore ${{env.sln-file}}
    - name: Build
      run: dotnet build ${{env.sln-file}} --configuration Release --no-restore
    - name: Test
      run: dotnet test ${{env.sln-file}} --no-restore --verbosity normal
